services:
  discord-overlord:
    build: .
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/fu/Server Stuff:/Users/fu/Server Stuff:ro
      - /Users/fu/Project:/Users/fu/Project:ro
    env_file: .env
